#!/usr/bin/env python
# Need to monkey patch stdlib before anything else is imported and has a chance to create threads.
import gevent; gevent.monkey.patch_all()  # noqa

import rospy
from std_msgs.msg import String

if __name__ == '__main__':
    rospy.init_node('gevent_publisher')
    pub = rospy.Publisher('string_topic', String, queue_size=1)
    r = rospy.Rate(1)

    while not rospy.is_shutdown():
        pub.publish('Published!')
        r.sleep()
