#!/usr/bin/env python
# Need to monkey patch stdlib before anything else is imported and has a chance to create threads.
from gevent import monkey
monkey.patch_all()  # noqa

import rospy
from std_srvs.srv import SetBool, SetBoolResponse


def service_handler(req):
    rospy.loginfo('Handled service request.')
    return SetBoolResponse(success=True, message='Handled.')


if __name__ == '__main__':
    rospy.init_node('patched_service_provider')
    s = rospy.Service('patched_service', SetBool, service_handler)
    rospy.spin()
