#!/usr/bin/env python
# Need to monkey patch stdlib before anything else is imported and has a chance to create threads.
from gevent import monkey, sleep
monkey.patch_all()  # noqa

import rospy
from std_srvs.srv import SetBool

'''
In this example we patch the stdlib (see other examples for more details), then send
'''

if __name__ == '__main__':
    rospy.init_node('patched_service_proxy')
    rospy.wait_for_service('patched_service')
    srv = rospy.ServiceProxy('patched_service', SetBool)

    while not rospy.is_shutdown():
        response = srv(True)
        rospy.loginfo('Got a response from service provider: {}'.format(response.message))
        sleep(1)
